### ISSUE TITLE
NullReferenceException when running OpenSession after attaching profiler

### ISSUE THREAD

**Issue by yellis** [csainty/MvcMiniProfiler.RavenDb#3]
Using the following code, run in an MVC4 app, in `Application_Start()`

```
var store = new DocumentStore {ConnectionStringName = "RavenDB"};
var DocumentStore = store.Initialize();
MvcMiniProfiler.RavenDb.Profiler.AttachTo(store);
using (var s = DocumentStore.OpenSession()) { ... }
```

Triggers a NullReferenceException error on the OpenSession function. Here is the stacktrace:

```
at MvcMiniProfiler.RavenDb.Profiler.TrackSession(InMemoryDocumentSessionOperations obj) in C:\Projects\OSS\MvcMiniProfiler.RavenDb\MvcMiniProfiler.RavenDb\Profiler.cs:line 21
at Raven.Client.Document.DocumentStore.AfterSessionCreated(InMemoryDocumentSessionOperations session) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Document\DocumentStore.cs:line 404
at Raven.Client.Document.DocumentStore.OpenSession() in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Document\DocumentStore.cs:line 325
at StatusBoard.Web.MvcApplication.InitializeDocumentStore() in C:\PATH-TO-PROJECT\Global.asax.cs:line 113
at StatusBoard.Web.MvcApplication.Application_Start() in C:\PATH-TO-PROJECT\Global.asax.cs:line 68
```

If I comment out the `AttachTo` function call then it works. Same error happens if I do not call `OpenSession()` within `Application_Start` but rather wait until the first request.

**Comment by csainty** [comment]
Try the latest build (v1.4) I added a few more != null checks.

**Comment by yellis** [comment]
That fixed it, thanks
